### ISSUE TITLE
BeDead needs a HVIF icon

### ISSUE THREAD

**Issue by AkshayAgarwal007** [HaikuArchives/BeDead#2]

**Comment by Meanwhile** [comment]
There's an icon called 'Misc_R.I.P' in Haiku's repo that may be suitable:
https://cgit.haiku-os.org/haiku/stats/data/artwork/icons/Misc_R.I.P

**Comment by Meanwhile** [comment]
Sorry, I should have added '...but it's not mine.' Thanks for crediting the icon creator though.

**Comment by AkshayAgarwal007** [comment]
I should have asked first actually and that's why I made the PR but I accidentally pushed it directly. That can be changed anyway because the original creator should be credited. But most of the places I came across have icons by you or Zumi so I thought it was created by you (as you commented).

Anyway can you help with the toolbar icons for [this](https://www.haiku-os.org/blog/akshayagarwal007/2017-07-25_gsoc_2017_calendar_app_weekly_report_5/).

**Comment by Meanwhile** [comment]
Fully understandable, no problem.
If Zumi's icons don't suffice, try contacting https://github.com/stippi
My attempt at 2D icons failed badly...
